// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
	LoginUser(ctx context.Context, username string) (LoginUserRow, error)
}

var _ Querier = (*Queries)(nil)
